---
management:
    endpoint:
        health:
            probes:
                enabled: true
    endpoints:
        web:
            exposure:
                include: health,env,metrics,beans,loggers,football
    tracing:
        sampling:
            probability: 1.0
        enabled: true
    otlp:
        tracing:
            endpoint: http://localhost:4317
spring:
    application:
        name: PlayerRanker
server:
    port: 9095